services:
  postgres:
    image: postgres
    ports:
      - "${PG_PORT}:5432"
    environment:
      - POSTGRES_DB=${PG_DATABASE_NAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    container_name: db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"] 
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - my-network

  balancer:
    image: balancer:v0.2
    ports:
      - "8080:8080"
    container_name: balancer
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my-network
    volumes:
      - "./config/config.yaml:/root/config/config.yaml"

networks:
  my-network:
    driver: bridge