services:
  postgres:
    image: postgres
    ports:
      - ${PG_PORT}:5432
    environment:
      - POSTGRES_DB=${PG_DATABASE_NAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    container_name: postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 5
    
  backend1:
    build:
      context: .
      dockerfile: backend-test.Dockerfile
    ports:
      - "8081:8081"
    environment:
      - HOST_PORT=0.0.0.0:8081
    container_name: backend1
    restart: unless-stopped
  
  backend2:
    build:
      context: .
      dockerfile: backend-test.Dockerfile
    ports:
      - "8082:8082"
    environment:
      - HOST_PORT=0.0.0.0:8082
    container_name: backend2
    restart: unless-stopped

  backend3:
    build:
      context: .
      dockerfile: backend-test.Dockerfile
    ports:
      - "8083:8083"
    environment:
      - HOST_PORT=0.0.0.0:8083
    container_name: backend3
    restart: unless-stopped

