server:
  host: localhost 
  port: 8080

ticker_rate_sec: 1

default_limits:
  capacity: 5
  rate_per_sec: 0.1

backend_list:
  - backend_url: http://localhost:8081
    config:
      health:
        method: HEAD
        url: /

  - backend_url: http://localhost:8082
    config:
      health:
        method: HEAD
        url: /

  - backend_url: http://localhost:8083
    config:
      health:
        method: HEAD
        url: /
