server:
  host: localhost
  port: 8080

db:
  db_host: localhost
  db_port: 5432
  db_name: clients_db
  db_user: admin
  db_password: 1234
  db_sslmode: disable

ticker_rate_sec: 5

defoult_limits:
  capasity: 3
  rate_per_sec: 0.3

backend_list:
  - backend_url: http://localhost:8081
    config:
      health:
        method: HEAD
        url: /

  - backend_url: http://localhost:8082
    config:
      health:
        method: HEAD
        url: /